# Generated by Django 3.1.6 on 2021-02-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
